TASK5: ready for review
Kernel-GL-HRK/gl_kernel_procamp_2021 pull request #133
Opened 2021-12-17 08:14 UTC by Vadym-tst

Signed-off-by: Vadym.Hutovskyi <vadym.hutovskyi@globallogic.com>

2021-12-17 09:04 UTC, ziod requested changes
pease do not use spaces in path.

2021-12-17 09:04 UTC, ziod commented on 05_timers/User space/user_space.c
> +static const char * const clock_id_name[] = {TO_STRING(CLOCK_REALTIME),
clock_id and clock_id_name may be consumed in one struct.

2021-12-17 09:04 UTC, ziod commented on 05_timers/User space/user_space.c
> +			return 1;
1; magic number

2021-12-17 11:37 UTC, Vadym-tst commented on 05_timers/Kernel space/kernel_space.c
> +#define ABSOLUTE_TIME_ATTRIBUTE_NAME	Absolute_time
negative. That is not a string data type

2021-12-17 16:13 UTC, ziod requested changes
Uninformatve commit message

2021-12-17 16:13 UTC, ziod commented on 05_timers/Kernel/kernel_space.c
> +	struct	timespec64 current_timestamp, delta_time;
Please do not define variables in coma separated way.

2021-12-17 16:13 UTC, ziod commented on 05_timers/Kernel/kernel_space.c
> +static ssize_t absolute_time(struct	kobject	*kobj, struct kobj_attribute *attr,	char *buf)
It is commn practice to name methods verb_subject.
show_absolufe_timestamp etc

2021-12-17 16:13 UTC, ziod commented on 05_timers/Kernel/kernel_space.c
> +			result =	-ENOMEM;
Unnecessary spaces

2021-12-17 16:13 UTC, ziod commented on 05_timers/Kernel/kernel_space.c
> +	sysfs_remove_file(time_module_kobject,	&relative_time_atr.attr);
Spaces

2021-12-17 16:13 UTC, ziod commented on 05_timers/User/user_space.c
> +	struct clock_id clocks[CLOCK_ID_MAX] = {
Can be static const

2021-12-17 16:13 UTC, ziod commented on 05_timers/User/user_space.c
> +			printf("Error %d: can't get current time\n", result);
It is better to keep one empty line after to increase readability

2021-12-17 18:41 UTC, ziod requested changes
please resolve all the comments

2021-12-17 18:41 UTC, ziod commented on 05_timers/Kernel/kernel_space.c
> +    struct	timespec64 delta_time;
please align

2021-12-21 14:30 UTC, ziod approved these changes

2021-12-21 14:32 UTC, merged