TASK1: Added implementation of rock-scissor-paper game
Kernel-GL-HRK/gl_kernel_procamp_2021 pull request #22
Opened 2021-11-22 11:21 UTC by MilosSomnium

2021-11-22 13:51 UTC, hrandib reviewed
It is a good style to add a new line at the end of each file

2021-11-22 14:01 UTC, hrandib commented on 01_git/main.c
> +    defualt:
You've declared a new label here, and this breaks the app workflow

2021-11-22 14:03 UTC, hrandib commented on 01_git/Makefile
> +	$(RM) *.o *.h.gch rsp_game
Please add an empty new line (and for other files)

2021-11-22 14:06 UTC, hrandib commented on 01_git/rock_scissors_paper.c
> +    return (enum GameValue) rand() % (Paper + 1);
It is better to declare the enum max index explicitly in the enum, as a last value

2021-11-22 14:09 UTC, hrandib requested changes
Please fix review comments

2021-11-22 14:49 UTC, MilosSomnium commented on 01_git/main.c
> +    enum GameValue user_move = Scissors;
Are there any preferences, if we know that value is set below and it cannot be uninitialized?

2021-11-23 11:40 UTC, hrandib commented on 01_git/main.c
> +    enum GameValue user_move = Scissors;
It is good practice for these cases to init it to the deliberately wrong value (enum could be extended). In this case you the mistyping of 'default' will be revealed in the earlier step.

2021-11-24 10:36 UTC, hrandib approved these changes

2021-11-24 11:37 UTC, merged