Vadym.hutovskyi
Kernel-GL-HRK/gl_kernel_procamp_2021 pull request #61
Opened 2021-11-26 10:37 UTC by Vadym-tst

Corrected according to last remarks.

2021-11-29 13:02 UTC, alexposukhov commented
Please set label "Ready for review" if your change is ready

2021-11-30 10:50 UTC, ziod requested changes

2021-11-30 10:50 UTC, ziod commented on 01_git/scissors/main.c
> +    const uint8_t buf_lenght = 16;
static or #define ... general C approach

2021-11-30 10:50 UTC, ziod commented on 01_git/scissors/main.c
> +        if(buf[0]!='y')
'y' is a magic number all constants shall be defined to increase flexibility

2021-11-30 10:50 UTC, ziod commented on 02_bash/hwdetect/hwdetect.sh
> +done
no new line at the end

2021-11-30 10:50 UTC, ziod commented on 02_bash/hwdetect/hwdetect.sh
> +
please remove spaces 4, 15, 18 rows. It is appliable for all 3 files in PR.

2021-11-30 10:50 UTC, ziod commented on 02_bash/hwdetect/hwdetect.sh
> +﻿#!/bin/bash
please squash with the previous.

2021-12-06 20:43 UTC, ziod requested changes

2021-12-06 20:43 UTC, ziod commented on 03_module/TASK3/TASK3.c
> +
WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
#1: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:1:
+

ERROR: trailing whitespace
#5: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:5:
+#include <linux/kernel.h> $

ERROR: trailing whitespace
#6: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:6:
+ $

WARNING: please, no spaces at the start of a line
#6: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:6:
+ $

ERROR: space required after that ',' (ctx:VxV)
#8: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:8:
+module_param(param_1,int,0660);
                     ^

ERROR: space required after that ',' (ctx:VxV)
#8: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:8:
+module_param(param_1,int,0660);
                         ^

ERROR: trailing whitespace
#9: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:9:
+ $

WARNING: please, no spaces at the start of a line
#9: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:9:
+ $

ERROR: space required after that ',' (ctx:VxV)
#11: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:11:
+module_param(param_2,int,0660);
                     ^

ERROR: space required after that ',' (ctx:VxV)
#11: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:11:
+module_param(param_2,int,0660);
                         ^

ERROR: trailing whitespace
#12: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:12:
+ $

WARNING: please, no spaces at the start of a line
#12: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:12:
+ $

WARNING: Prefer [subsystem eg: netdev]_warn([subsystem]dev, ... then dev_warn(dev, ... then pr_warn(...  to printk(KERN_WARNING ...
#15: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:15:
+	printk(KERN_WARNING "Start: param_1=%d, param_2=%d, param_1+param_2=%d\n", param_1, param_2, param_1+param_2);

ERROR: trailing whitespace
#18: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:18:
+ $

WARNING: please, no spaces at the start of a line
#18: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:18:
+ $

WARNING: Prefer [subsystem eg: netdev]_warn([subsystem]dev, ... then dev_warn(dev, ... then pr_warn(...  to printk(KERN_WARNING ...
#21: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:21:
+	printk(KERN_WARNING "Stop: param_1=%d, param_2=%d, param_1-param_2=%d\n", param_1, param_2, param_1-param_2);

ERROR: trailing whitespace
#23: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:23:
+ $

WARNING: please, no spaces at the start of a line
#23: FILE: /air/Documents/trainings/linux/kernel/pro-camp/2021/03_module/TASK3/TASK3.c:23:
+ $

total: 10 errors, 8 warnings, 30 lines checked

2021-12-13 19:38 UTC, ziod requested changes

2021-12-13 19:38 UTC, ziod commented on 04_basic_struct/TASK4/TASK4.c
> +	return count;
strlen(buf)

2021-12-15 11:40 UTC, closed without merging