03 git solution
Kernel-GL-HRK/gl_kernel_procamp_2021 pull request #89
Opened 2021-12-03 10:27 UTC by SyedinSN

Completed the assignment according to the requirements for lesson 3

2021-12-04 15:34 UTC, alexposukhov commented
Please rename pull request description according to current task

2021-12-04 15:38 UTC, alexposukhov requested changes
Please use checkpatch.pl script to fix warnings and errors.

2021-12-04 15:38 UTC, alexposukhov commented on 03_module/hello_mod.c
> +static int a=10;
Please set initial value to 0

2021-12-04 15:38 UTC, alexposukhov commented on 03_module/hello_mod.c
> +static int b=15;
Same here

2021-12-04 15:42 UTC, alexposukhov commented
Please note that parameter should be transferred to module during loading:
`$insmod hello_mod.ko a=5 b= 7`

2021-12-06 20:24 UTC, SyedinSN reviewed
fulfilled all the indicated comments

2021-12-06 20:26 UTC, SyedinSN commented
Changes according to the comments were made in branch 03_module_solution

2021-12-09 06:27 UTC, closed without merging